### ISSUE TITLE
[Feature Request][Move Package System] support dependencies from remote locations like git

### ISSUE THREAD

**Issue by lerencao** [diem/diem#9275]
# 🚀 Feature Request

Support to declare dependencies from remote location like github, even directly from onchain.

## Motivation

Move Package System is a big improvement for developing Move DAPPs. However, only local dependencies(local paths) are supported in the Move.toml, which is hard to  share codes between several parties. So I propose the request of fetching deps from remote locations.

## Pitch

The following remote dependencies are general-used:

- git repo, like github, bitbucket.
- centralized servers, like crates.io does for rust packages.
- decentralized servers, like ipfs.

A possible syntax in Move.toml may like this:

```toml
[dependencies]
PkgA = {git="https://github.com/diem/demo-package"}
# or in sub dir
PkgB = {git="https://github.com/diem/demo-packages", sub_dir="./subdirs/packageb"}
```

However, two different dependencies may depend on different revisions of a same package. How to resolve and compile the different revisions is a big problem in Move.

An alternative is declaring dependencies directly from onchain modules.

As only one bytecode exists for a particular module, one can declare dependency on modules directly.

like:

```toml
[addresses]
A="0x3"
B="0x4"
[dependencies]
ModuleA = {remote="https://movechain.io/rpc/modules", address="A", name="ModuleA"}
RenamedB = {remote="https://movechain.io/rpc/modules", address="B", name="ModuleB"}
ModuleC = {remote="https://movechain.io/rpc/modules", address="A"}
```

However the approach need a solution to generalize the interface of remote fetching of modules on blockchains of different apis.
